import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {products} from './data';
import './styles.css';

const money = n => `$${n.toFixed(2)}`;

function ArrowIcon(){return <svg className="arrow-icon" viewBox="0 0 20 20" aria-hidden="true"><path d="M5 15 15 5M7 5h8v8"/></svg>}

function Can({product, hero=false}){
  return <div className={`can can-${product.variant} ${hero?'hero-can':''}`} style={{'--can':product.color,'--ink':product.accent}} aria-label={`${product.name} — банка`}>
    <span className="can-top"/><span className="can-logo">MOYO</span><span className="can-line"/>
    <strong>{product.mood}</strong><small>{product.purpose}</small><b>0<br/><i>сахара</i></b>
  </div>
}

function Header({count,onCart}){
  const [open,setOpen]=useState(false);
  return <header><a className="logo" href="#top">MOYO<span>°</span></a>
    <nav className="desktop-nav"><a href="#shop">Магазин</a><a href="#benefits">Преимущества</a><a href="#ingredients">Состав</a><a href="#about">О нас</a></nav>
    <div className="actions"><button aria-label="Поиск"><svg className="search-icon" viewBox="0 0 20 20" aria-hidden="true"><circle cx="9" cy="9" r="5.5"/><path d="m13 13 4 4"/></svg></button><button className="account" aria-label="Аккаунт">Аккаунт</button><button onClick={onCart}>Корзина <em className="cart-count">{count}</em></button><button className={`hamb ${open?'active':''}`} aria-label="Меню" onClick={()=>setOpen(!open)}><i/><i/></button></div>
    <div className={`mobile-menu ${open?'open':''}`}><small>Откройте MOYO</small>{[['Магазин','shop'],['Преимущества','benefits'],['Состав','ingredients'],['О нас','about']].map(x=><a key={x[1]} onClick={()=>setOpen(false)} href={`#${x[1]}`}>{x[0]}</a>)}<div>Инстаграм ↗ &nbsp; ТикТок ↗</div></div>
  </header>
}

function Hero({add}){
  return <section className="hero" id="top"><div className="hero-copy reveal"><p className="eyebrow">ФУНКЦИОНАЛЬНЫЙ НАПИТОК · 01</p><h1>Чувствуй больше.<br/><i>Пей лучше.</i></h1><p className="lede">Восемь напитков для восьми конкретных задач. Натуральные вкусы, понятный состав и свой MOYO для каждого момента дня.</p><button className="pill dark magnetic" onClick={()=>document.querySelector('#shop').scrollIntoView()}>Смотреть коллекцию <ArrowIcon/></button></div>
    <div className="hero-art"><div className="orb"/><Can product={products[0]} hero/><span className="float-label l1">БЕЗ<br/>САХАРА</span><span className="float-label l2">ПРИРОДНАЯ<br/>ЭНЕРГИЯ</span><div className="scribble">здесь живёт<br/>хорошая энергия ↓</div></div>
    <div className="marquee"><div>ЭНЕРГИЯ · ПРОТЕИН · КОЛЛАГЕН · ФОКУС · ВОССТАНОВЛЕНИЕ · РЕЛАКС · ГИДРАТАЦИЯ · ИММУНИТЕТ · ЭНЕРГИЯ · ПРОТЕИН · КОЛЛАГЕН · ФОКУС ·</div></div>
  </section>
}

function Benefits(){return <section className="benefits section" id="benefits"><div className="section-head"><p className="eyebrow">Почему MOYO</p><h2>Только полезное.<br/><i>Нечего скрывать.</i></h2></div><div className="benefit-grid">{[['01','Без добавленного сахара','Яркий вкус — без резкого спада сил.'],['02','Натуральные ингредиенты','Растения, фрукты и полезные растительные компоненты.'],['03','Витамины и минералы','Точная дозировка для ежедневной поддержки.'],['04','Забота о планете','Алюминиевые банки можно перерабатывать снова и снова.']].map(x=><article className="reveal" key={x[0]}><span>{x[0]}</span><div className={`benefit-icon benefit-icon-${x[0]}`} aria-hidden="true"/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>}

function Shop({add}){return <section className="shop section" id="shop"><div className="section-head row"><div><p className="eyebrow">КОЛЛЕКЦИЯ MOYO</p><h2>Выберите свою<br/><i>задачу на сегодня.</i></h2></div><p>Восемь разных формул.<br/>Один понятный выбор.</p></div><div className="product-grid">{products.map((p,i)=><article className="product reveal" key={p.id}><div className="product-visual" style={{background:p.color}}><span>0{i+1}</span><Can product={p}/><button className="quick" aria-label={`Добавить ${p.name} в корзину`} onClick={()=>add(p)}>+</button></div><div className="product-info"><p className="tag">{p.mood}</p><h3>{p.name}</h3><p className="product-purpose">{p.purpose}</p><p className="product-description">{p.description}</p><small>{p.note}</small></div><button className="add" onClick={()=>add(p)}><span className="add-label">В корзину</span><span className="add-meta"><strong>{money(p.price)}</strong><i aria-hidden="true">→</i></span></button></article>)}</div></section>}

function Mood({add}){const [mood,setMood]=useState('Энергия'); const p=products.find(x=>x.mood===mood);return <section className="mood section"><div className="mood-copy"><p className="eyebrow">ПОДБОР ПО ЗАДАЧЕ</p><h2>Что вам<br/><i>нужно сегодня?</i></h2><div className="mood-buttons">{products.map(x=><button className={mood===x.mood?'active':''} onClick={()=>setMood(x.mood)} key={x.mood}><span>{x.mood}<small>{x.purpose}</small></span><ArrowIcon/></button>)}</div></div><div className="mood-result" style={{background:p.color}}><div className="mood-text"><small>{p.purpose}</small><h3>{p.name}</h3><p>{p.description}</p><b>{p.note}</b><button className="pill dark mood-add" onClick={()=>add(p)}><span>В корзину</span><strong>{money(p.price)}</strong></button></div><Can key={p.id} product={p}/></div></section>}

function Ingredients(){return <section className="ingredients section" id="ingredients"><div className="ingredient-art"><div className="fruit fruit1"/><div className="fruit fruit2"/><Can product={products[3]}/><span className="vit v1">B12</span><span className="vit v2">Mg</span><span className="leaf"/></div><div className="ingredient-copy"><p className="eyebrow">ЧТО ВНУТРИ</p><h2>Сила<br/><i>настоящей природы.</i></h2><p>Знакомые фрукты сочетаются с продуманными функциональными ингредиентами. У каждого компонента есть цель — ничего лишнего.</p>{['Экстракты настоящих фруктов','Адаптогены и растения','Необходимые витамины','Без искусственных подсластителей'].map((x,i)=><div className="ingredient-row" key={x}><span>0{i+1}</span><strong>{x}</strong><b>+</b></div>)}</div></section>}

function Reviews(){return <section className="reviews section"><div className="section-head row"><div><p className="eyebrow">ОТЗЫВЫ СООБЩЕСТВА</p><h2>Любят<br/><i>по-настоящему.</i></h2></div><div className="stars">★★★★★ <small>4.9 / 5</small></div></div><div className="review-grid">{[['«Послеобеденная усталость наконец исчезла. MOYO Энергия — яркий, не слишком сладкий и действительно работает».','МАЙЯ Р.','Проверенный покупатель'],['«Это приятный маленький ритуал, а не очередная добавка. MOYO Релакс теперь всегда в моём холодильнике».','ОЛИВИЯ К.','Ежемесячная подписка'],['«Красивые банки, изысканный вкус и никакого странного послевкусия. MOYO Фокус — мой секрет в дни встреч».','ДЖЕЙМС Т.','Проверенный покупатель']].map((r,i)=><article key={i}><div>★★★★★</div><blockquote>{r[0]}</blockquote><footer><span className="avatar">{r[1][0]}</span><strong>{r[1]}<small>{r[2]}</small></strong></footer></article>)}</div></section>}

function Subscribe(){return <section className="subscribe section" id="about"><div><p className="eyebrow">MOYO СНОВА И СНОВА</p><h2>Хорошее настроение<br/><i>с доставкой.</i></h2><p>Соберите ежемесячный набор и сэкономьте 15%. Пропускайте или отменяйте доставку когда угодно. Ваш холодильник — ваши правила.</p><button className="pill light">Оформить подписку <span>→</span></button></div><div className="sub-art"><Can product={products[2]}/><Can product={products[0]}/><Can product={products[3]}/><span>СКИДКА<br/><b>15%</b></span></div></section>}

function Newsletter(){const [done,setDone]=useState(false);return <section className="newsletter"><p className="eyebrow">ВЕСТОЧКА ОТ MOYO</p><h2>{done?'Вы в списке.':'Будьте в курсе.'}</h2><p>{done?'Приятные новости уже летят на вашу почту.':'Новинки, советы для настроения и скидка 15% на первый заказ.'}</p>{!done&&<form onSubmit={e=>{e.preventDefault();setDone(true)}}><input required type="email" placeholder="Ваш электронный адрес" aria-label="Электронный адрес"/><button>Подписаться →</button></form>}</section>}

function Footer(){return <footer className="site-footer"><div className="footer-top"><a className="logo">MOYO<span>°</span></a><div><strong>Разделы</strong><a href="#shop">Магазин</a><a href="#benefits">Преимущества</a><a href="#ingredients">Состав</a></div><div><strong>Помощь</strong><a>Вопросы и ответы</a><a>Доставка</a><a href="mailto:hello@moyo.com">Контакты</a></div><div><strong>Соцсети</strong><a>Инстаграм ↗</a><a>ТикТок ↗</a></div></div><div className="footer-word">MOYO</div><div className="footer-bottom"><span>© 2026 НАПИТКИ MOYO</span><a>Политика конфиденциальности</a><a>Условия</a><span>ЧУВСТВУЙ БОЛЬШЕ. ПЕЙ ЛУЧШЕ.</span></div></footer>}

function Cart({items,setItems,onCheckout}){const total=items.reduce((s,x)=>s+x.price*x.qty,0);const change=(id,n)=>setItems(items.map(x=>x.id===id?{...x,qty:Math.max(1,x.qty+n)}:x));return <div className="cart-page page-in"><div className="cart-title"><p className="eyebrow">ВАШ ВЫБОР</p><h1>Ваша корзина <i>({items.reduce((s,x)=>s+x.qty,0)})</i></h1></div>{items.length===0?<div className="empty"><h2>Ваш холодильник хочет пить.</h2><button className="pill dark" onClick={()=>location.hash=''}>Выбрать напитки</button></div>:<div className="cart-layout"><div>{items.map(x=><article className="cart-item" key={x.id}><div style={{background:x.color}}><Can product={x}/></div><section><span className="tag">{x.mood}</span><h3>{x.name}</h3><p>{x.note}</p><button onClick={()=>setItems(items.filter(i=>i.id!==x.id))}>Удалить</button></section><div className="qty"><button onClick={()=>change(x.id,-1)}>−</button><span>{x.qty}</span><button onClick={()=>change(x.id,1)}>+</button></div><strong>{money(x.price*x.qty)}</strong></article>)}</div><aside className="summary"><h2>Состав заказа</h2><p><span>Товары</span><b>{money(total)}</b></p><p><span>Доставка</span><b>{total>35?'Бесплатно':'$4.90'}</b></p><hr/><p className="total"><span>Итого</span><b>{money(total+(total>35?0:4.9))}</b></p><button className="pill dark" onClick={onCheckout}>Оформить →</button><small>Налоги рассчитываются при оформлении · Безопасное оформление</small></aside></div>}</div>}

function Checkout({items,onSuccess}){const total=items.reduce((s,x)=>s+x.price*x.qty,0), shipping=total>35?0:4.9;return <main className="checkout page-in"><div className="checkout-form"><button className="back" onClick={()=>location.hash='cart'}>← Назад в корзину</button><p className="eyebrow">ОФОРМЛЕНИЕ ЗАКАЗА</p><h1>Почти <i>у вас.</i></h1><form id="order" onSubmit={e=>{e.preventDefault();onSuccess()}}><div className="field-grid"><label>Имя<input required/></label><label>Фамилия<input required/></label></div><label>Электронная почта<input required type="email"/></label><label>Телефон<input required type="tel"/></label><label>Страна<select required defaultValue=""><option value="" disabled>Выберите страну</option><option>США</option><option>Великобритания</option><option>Канада</option><option>Германия</option><option>Франция</option></select></label><div className="field-grid"><label>Город<input required/></label><label>Индекс<input required/></label></div><label>Адрес<input required/></label><button className="pill dark order-mobile">Оформить заказ · {money(total+shipping)}</button></form></div><aside className="order-summary"><p className="eyebrow">СОСТАВ ЗАКАЗА</p>{items.map(x=><div className="mini-item" key={x.id}><div style={{background:x.color}}><Can product={x}/><em>{x.qty}</em></div><span><b>{x.name}</b><small>{x.mood}</small></span><strong>{money(x.price*x.qty)}</strong></div>)}<hr/><p><span>Товары</span><b>{money(total)}</b></p><p><span>Доставка</span><b>{shipping?'$4.90':'Бесплатно'}</b></p><p className="total"><span>Итого</span><b>{money(total+shipping)}</b></p><button form="order" className="pill dark">Оформить заказ →</button><small className="demo-note">Демонстрационное оформление · Оплата не списывается</small></aside></main>}

function Success(){return <main className="success page-in"><div className="success-orb"><div className="check">✓</div><span>ЗАКАЗ ПОДТВЕРЖДЁН</span></div><p className="eyebrow">СПАСИБО</p><h1>Хорошее настроение<br/><i>уже в пути.</i></h1><p>Заказ <b>#MYO-24018</b> подтверждён. Все вкусные подробности отправлены на вашу почту.</p><button className="pill dark" onClick={()=>location.hash=''}>Вернуться в MOYO →</button><div className="success-cans"><Can product={products[1]}/><Can product={products[0]}/><Can product={products[2]}/></div></main>}

function App(){const [items,setItems]=useState(()=>JSON.parse(localStorage.getItem('moyo-cart')||'[]'));const [route,setRoute]=useState(location.hash.slice(1));const [toast,setToast]=useState('');useEffect(()=>{localStorage.setItem('moyo-cart',JSON.stringify(items))},[items]);useEffect(()=>{const fn=()=>{setRoute(location.hash.slice(1));scrollTo(0,0)};addEventListener('hashchange',fn);return()=>removeEventListener('hashchange',fn)},[]);useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('seen')),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));return()=>io.disconnect()},[route]);const add=p=>{setItems(v=>{const old=v.find(x=>x.id===p.id);return old?v.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...v,{...p,qty:1}]});setToast(`${p.name} добавлен в корзину`);setTimeout(()=>setToast(''),1800)};const count=items.reduce((s,x)=>s+x.qty,0);let page;if(route==='cart')page=<Cart items={items} setItems={setItems} onCheckout={()=>location.hash='checkout'}/>;else if(route==='checkout')page=<Checkout items={items} onSuccess={()=>{setItems([]);location.hash='success'}}/>;else if(route==='success')page=<Success/>;else page=<main><Hero add={add}/><Benefits/><Shop add={add}/><Mood add={add}/><Ingredients/><Reviews/><Subscribe/><Newsletter/><Footer/></main>;return <><Header count={count} onCart={()=>location.hash='cart'}/>{page}<div className={`toast ${toast?'show':''}`}>✓ {toast}</div></>}

createRoot(document.getElementById('root')).render(<App/>);
