import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {products} from './data';
import './styles.css';

const money = n => `$${n.toFixed(2)}`;

function Can({product, hero=false}){
  return <div className={`can ${hero?'hero-can':''}`} style={{'--can':product.color,'--ink':product.accent}} aria-label={`${product.name} can`}>
    <span className="can-top"/><span className="can-logo">MOYO</span><span className="can-line"/>
    <strong>{product.mood}</strong><small>{product.note.split(' · ')[0]} functional soda</small><b>0<br/><i>sugar</i></b>
  </div>
}

function Header({count,onCart}){
  const [open,setOpen]=useState(false);
  return <header><a className="logo" href="#top">MOYO<span>°</span></a>
    <nav className="desktop-nav"><a href="#shop">Shop</a><a href="#benefits">Benefits</a><a href="#ingredients">Ingredients</a><a href="#about">About</a></nav>
    <div className="actions"><button aria-label="Search">⌕</button><button className="account" aria-label="Account">Account</button><button onClick={onCart}>Cart <em className="cart-count">{count}</em></button><button className={`hamb ${open?'active':''}`} aria-label="Menu" onClick={()=>setOpen(!open)}><i/><i/></button></div>
    <div className={`mobile-menu ${open?'open':''}`}><small>Explore MOYO</small>{['Shop','Benefits','Ingredients','About'].map(x=><a key={x} onClick={()=>setOpen(false)} href={`#${x.toLowerCase()}`}>{x}</a>)}<div>Instagram ↗ &nbsp; TikTok ↗</div></div>
  </header>
}

function Hero({add}){
  return <section className="hero" id="top"><div className="hero-copy reveal"><p className="eyebrow">FUNCTIONAL SODA · 01</p><h1>Feel more.<br/><i>Drink better.</i></h1><p className="lede">Four moods. Real ingredients. Zero added sugar. A daily ritual designed around how you want to feel.</p><button className="pill dark magnetic" onClick={()=>document.querySelector('#shop').scrollIntoView()}>Shop the collection <span>↗</span></button></div>
    <div className="hero-art"><div className="orb"/><Can product={products[0]} hero/><span className="float-label l1">ZERO<br/>ADDED SUGAR</span><span className="float-label l2">NATURAL<br/>ENERGY</span><div className="scribble">good energy<br/>lives here ↓</div></div>
    <div className="marquee"><div>ENERGY ✦ FOCUS ✦ RECOVERY ✦ RELAX ✦ ENERGY ✦ FOCUS ✦ RECOVERY ✦ RELAX ✦</div></div>
  </section>
}

function Benefits(){return <section className="benefits section" id="benefits"><div className="section-head"><p className="eyebrow">Why MOYO</p><h2>Only the good stuff.<br/><i>Nothing to hide.</i></h2></div><div className="benefit-grid">{[['01','Zero added sugar','Bright flavor, never the crash.'],['02','Natural ingredients','Plants, fruits and functional botanicals.'],['03','Vitamins & minerals','Thoughtfully dosed for everyday support.'],['04','Planet in mind','Infinitely recyclable aluminum cans.']].map(x=><article className="reveal" key={x[0]}><span>{x[0]}</span><div className="benefit-icon">{['✦','✿','☼','♲'][+x[0]-1]}</div><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>}

function Shop({add}){return <section className="shop section" id="shop"><div className="section-head row"><div><p className="eyebrow">THE CORE FOUR</p><h2>Meet your<br/><i>daily moods.</i></h2></div><p>Made to meet you where you are,<br/>and move you where you want to go.</p></div><div className="product-grid">{products.map((p,i)=><article className="product reveal" key={p.id}><div className="product-visual" style={{background:p.color}}><span>0{i+1}</span><Can product={p}/><button className="quick" onClick={()=>add(p)}>+</button></div><div className="product-info"><div><p className="tag">{p.mood}</p><h3>{p.name}</h3><small>{p.note}</small></div><strong>{money(p.price)}</strong></div><button className="add" onClick={()=>add(p)}>Add to cart <span>→</span></button></article>)}</div></section>}

function Mood({add}){const [mood,setMood]=useState('Energy'); const p=products.find(x=>x.mood===mood);return <section className="mood section"><div className="mood-copy"><p className="eyebrow">MOOD MATCHER</p><h2>What do you<br/><i>need today?</i></h2><div className="mood-buttons">{products.map(x=><button className={mood===x.mood?'active':''} onClick={()=>setMood(x.mood)} key={x.mood}>{x.mood}<span>↗</span></button>)}</div></div><div className="mood-result" style={{background:p.color}}><div className="mood-text"><small>Your match</small><h3>{p.name}</h3><p>{p.note}</p><button className="pill dark" onClick={()=>add(p)}>Add to cart · {money(p.price)}</button></div><Can key={p.id} product={p}/></div></section>}

function Ingredients(){return <section className="ingredients section" id="ingredients"><div className="ingredient-art"><div className="fruit fruit1">🍋</div><div className="fruit fruit2">🫐</div><Can product={products[1]}/><span className="vit v1">B12</span><span className="vit v2">Mg</span><span className="leaf">☘</span></div><div className="ingredient-copy"><p className="eyebrow">INSIDE THE CAN</p><h2>Powered by<br/><i>real nature.</i></h2><p>Familiar fruits meet clever functional ingredients. Everything has a purpose. Nothing is there just to fill the label.</p>{['Real fruit extracts','Adaptogens & botanicals','Essential vitamins','No artificial sweeteners'].map((x,i)=><div className="ingredient-row" key={x}><span>0{i+1}</span><strong>{x}</strong><b>+</b></div>)}</div></section>}

function Reviews(){return <section className="reviews section"><div className="section-head row"><div><p className="eyebrow">COMMUNITY NOTES</p><h2>Loved in<br/><i>real life.</i></h2></div><div className="stars">★★★★★ <small>4.9 / 5</small></div></div><div className="review-grid">{[['“My 3pm slump has officially left the chat. Citrus Charge is bright, not too sweet, and genuinely works.”','MAYA R.','Verified buyer'],['“It feels like a little ritual instead of another supplement. Pear Still lives permanently in my fridge.”','OLIVIA K.','Monthly subscriber'],['“Beautiful cans, sophisticated flavor, zero weird aftertaste. Berry Clarity is my meeting-day secret.”','JAMES T.','Verified buyer']].map((r,i)=><article key={i}><div>★★★★★</div><blockquote>{r[0]}</blockquote><footer><span className="avatar">{r[1][0]}</span><strong>{r[1]}<small>{r[2]}</small></strong></footer></article>)}</div></section>}

function Subscribe(){return <section className="subscribe section" id="about"><div><p className="eyebrow">MOYO ON REPEAT</p><h2>Good moods,<br/><i>delivered.</i></h2><p>Build your monthly box and save 15%. Skip or cancel whenever. Your fridge, your rules.</p><button className="pill light">Start a subscription <span>→</span></button></div><div className="sub-art"><Can product={products[2]}/><Can product={products[0]}/><Can product={products[3]}/><span>SAVE<br/><b>15%</b></span></div></section>}

function Newsletter(){const [done,setDone]=useState(false);return <section className="newsletter"><p className="eyebrow">A NOTE FROM MOYO</p><h2>{done?'You’re on the list.':'Stay in the loop.'}</h2><p>{done?'Good things are heading to your inbox.':'New drops, mood tips, and 15% off your first order.'}</p>{!done&&<form onSubmit={e=>{e.preventDefault();setDone(true)}}><input required type="email" placeholder="Your email address" aria-label="Email address"/><button>Join us →</button></form>}</section>}

function Footer(){return <footer className="site-footer"><div className="footer-top"><a className="logo">MOYO<span>°</span></a><div><strong>Explore</strong><a href="#shop">Shop</a><a href="#benefits">Benefits</a><a href="#ingredients">Ingredients</a></div><div><strong>Help</strong><a>FAQ</a><a>Shipping</a><a href="mailto:hello@moyo.com">Contacts</a></div><div><strong>Social</strong><a>Instagram ↗</a><a>TikTok ↗</a></div></div><div className="footer-word">MOYO</div><div className="footer-bottom"><span>© 2026 MOYO DRINKS</span><a>Privacy Policy</a><a>Terms</a><span>FEEL MORE. DRINK BETTER.</span></div></footer>}

function Cart({items,setItems,onCheckout}){const total=items.reduce((s,x)=>s+x.price*x.qty,0);const change=(id,n)=>setItems(items.map(x=>x.id===id?{...x,qty:Math.max(1,x.qty+n)}:x));return <div className="cart-page page-in"><div className="cart-title"><p className="eyebrow">YOUR SELECTION</p><h1>Your cart <i>({items.reduce((s,x)=>s+x.qty,0)})</i></h1></div>{items.length===0?<div className="empty"><h2>Your fridge looks thirsty.</h2><button className="pill dark" onClick={()=>location.hash=''}>Shop drinks</button></div>:<div className="cart-layout"><div>{items.map(x=><article className="cart-item" key={x.id}><div style={{background:x.color}}><Can product={x}/></div><section><span className="tag">{x.mood}</span><h3>{x.name}</h3><p>{x.note}</p><button onClick={()=>setItems(items.filter(i=>i.id!==x.id))}>Remove</button></section><div className="qty"><button onClick={()=>change(x.id,-1)}>−</button><span>{x.qty}</span><button onClick={()=>change(x.id,1)}>+</button></div><strong>{money(x.price*x.qty)}</strong></article>)}</div><aside className="summary"><h2>Order summary</h2><p><span>Subtotal</span><b>{money(total)}</b></p><p><span>Shipping</span><b>{total>35?'Free':'$4.90'}</b></p><hr/><p className="total"><span>Total</span><b>{money(total+(total>35?0:4.9))}</b></p><button className="pill dark" onClick={onCheckout}>Checkout →</button><small>Taxes calculated at checkout · Secure checkout</small></aside></div>}</div>}

function Checkout({items,onSuccess}){const total=items.reduce((s,x)=>s+x.price*x.qty,0), shipping=total>35?0:4.9;return <main className="checkout page-in"><div className="checkout-form"><button className="back" onClick={()=>location.hash='cart'}>← Back to cart</button><p className="eyebrow">CHECKOUT</p><h1>Almost <i>yours.</i></h1><form id="order" onSubmit={e=>{e.preventDefault();onSuccess()}}><div className="field-grid"><label>First name<input required/></label><label>Last name<input required/></label></div><label>Email<input required type="email"/></label><label>Phone<input required type="tel"/></label><label>Country<select required defaultValue=""><option value="" disabled>Select country</option><option>United States</option><option>United Kingdom</option><option>Canada</option><option>Germany</option><option>France</option></select></label><div className="field-grid"><label>City<input required/></label><label>Postal code<input required/></label></div><label>Address<input required/></label><button className="pill dark order-mobile">Place order · {money(total+shipping)}</button></form></div><aside className="order-summary"><p className="eyebrow">ORDER SUMMARY</p>{items.map(x=><div className="mini-item" key={x.id}><div style={{background:x.color}}><Can product={x}/><em>{x.qty}</em></div><span><b>{x.name}</b><small>{x.mood}</small></span><strong>{money(x.price*x.qty)}</strong></div>)}<hr/><p><span>Subtotal</span><b>{money(total)}</b></p><p><span>Shipping</span><b>{shipping?'$4.90':'Free'}</b></p><p className="total"><span>Total</span><b>{money(total+shipping)}</b></p><button form="order" className="pill dark">Place order →</button><small className="demo-note">Demo checkout · No payment will be taken</small></aside></main>}

function Success(){return <main className="success page-in"><div className="success-orb"><div className="check">✓</div><span>ORDER CONFIRMED</span></div><p className="eyebrow">THANK YOU</p><h1>Your good mood<br/><i>is on its way.</i></h1><p>Order <b>#MYO-24018</b> is confirmed. We’ve sent all the delicious details to your inbox.</p><button className="pill dark" onClick={()=>location.hash=''}>Back to MOYO →</button><div className="success-cans"><Can product={products[1]}/><Can product={products[0]}/><Can product={products[2]}/></div></main>}

function App(){const [items,setItems]=useState(()=>JSON.parse(localStorage.getItem('moyo-cart')||'[]'));const [route,setRoute]=useState(location.hash.slice(1));const [toast,setToast]=useState('');useEffect(()=>{localStorage.setItem('moyo-cart',JSON.stringify(items))},[items]);useEffect(()=>{const fn=()=>{setRoute(location.hash.slice(1));scrollTo(0,0)};addEventListener('hashchange',fn);return()=>removeEventListener('hashchange',fn)},[]);useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('seen')),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));return()=>io.disconnect()},[route]);const add=p=>{setItems(v=>{const old=v.find(x=>x.id===p.id);return old?v.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...v,{...p,qty:1}]});setToast(`${p.name} added`);setTimeout(()=>setToast(''),1800)};const count=items.reduce((s,x)=>s+x.qty,0);let page;if(route==='cart')page=<Cart items={items} setItems={setItems} onCheckout={()=>location.hash='checkout'}/>;else if(route==='checkout')page=<Checkout items={items} onSuccess={()=>{setItems([]);location.hash='success'}}/>;else if(route==='success')page=<Success/>;else page=<main><Hero add={add}/><Benefits/><Shop add={add}/><Mood add={add}/><Ingredients/><Reviews/><Subscribe/><Newsletter/><Footer/></main>;return <><Header count={count} onCart={()=>location.hash='cart'}/>{page}<div className={`toast ${toast?'show':''}`}>✓ {toast}</div></>}

createRoot(document.getElementById('root')).render(<App/>);
